#!/usr/bin/env python

"""
adds prefix to commit message in square brackets
e.g., if branch name is api-cristian and we run:
git commit -m "fix header"
then commit message will look like:
[api-cristian]: fix header
"""

import sys
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()

with open(commit_msg_filepath, 'r+') as f:
	commit_msg = f.read()
	f.seek(0, 0)
	f.write("[{}]: {}".format(branch, commit_msg))
