import json
import json_flatten
import sys
import os

def clean_empty(d):
    if not isinstance(d, (dict, list)):
        return d
    if isinstance(d, list):
        return [v for v in (clean_empty(v) for v in d) if v]
    return {k: v for k, v in ((k, clean_empty(v)) for k, v in d.items()) if v}

def make_lowercase(obj):
    if hasattr(obj,'iteritems'):
        # dictionary
        ret = {}
        for k,v in obj.iteritems():
            ret[make_lowercase(k)] = make_lowercase(v)
        return ret
    elif isinstance(obj,str):
        # string
        return obj.lower()
    elif hasattr(obj,'__iter__'):
        # list (or the like)
        ret = []
        for item in obj:
            ret.append(make_lowercase(item))
        return ret
    else:
        # anything else
        return obj

def json_diff(left: dict, right: dict, custom_mappings: dict) -> dict:
    '''
    Compute difference between left and right JSON objects

    :param dict left: left JSON object (original JSON)  
    :param dict right: right JSON object (JSON generated by MSP)
    :param dict custom_mappings: JSON object detailing left to right custom mappings
    :return difference between left and right JSON objects    
    :rtype: dict
    '''

    # print("Flattening 'left' JSON...")
    left_flattened = json_flatten.flatten(left)

    # print("Convert 'left' JSON keys to lowercase...")
    left_flattened = {k.lower(): v for k, v in left_flattened.items()}

    # print("Flattening 'right' JSON...")
    right_flattened = json_flatten.flatten(right)    

    # print("Convert 'right' JSON keys to lowercase...")
    # right_flattened = {k.lower(): v for k, v in right_flattened.items() if v != "" and v != 'None'}
    right_flattened = {k.lower(): v for k, v in right_flattened.items()}    

    diff = {}

    # print("original JSON size = " + str(len(left_flattened)))
    # print("new JSON size = " + str(len(right_flattened)))

    diff["DiffStatistics"] = {
        "OriginalJSONSize": str(len(left_flattened)),
        "NewJSONSize": len(right_flattened),
        "Delta": abs(len(left_flattened) - len(right_flattened))        
    }

    found_diff: bool = False

    '''
    Validate that all keys from left JSON exist in generated JSON
    and that their values correspond.
    '''
    for k, v in left_flattened.items():
        k = handle_custom_mapping(k, custom_mappings)

        path = ""
        val = clean_empty(right)
        val = eval(repr(val).lower()) # set val to original right dictionary, where everything is lowercase
        replace_key = False
        for key in k.split("."): 
            if key.isnumeric() == False and key not in val:
                path += key
                break
            if key in val:
                if isinstance(val[key], list) and len(val[key]) == 1:
                    replace_key = True
                    path += key + ".0."
                    val = val[key][0]
                else:                                
                    path += key + "."                
                    val = val[key]        
            if key.isnumeric():                              
                path += key + "."            
                val = val[int(key)]            

        if path[len(path) - 1] == ".":
            path = path[:len(path) - 1] # remove last "."

        if replace_key: 
            k = path       

        if k not in right_flattened:
            diff[k] = {
                "Explanation": "Key '{}' with value '{}' is not present in right JSON".format(k, v)
            }
            found_diff = True   
        elif right_flattened[k] != v:      
            diff[k] = {
                "Explanation": "Value at key '{}' does not match".format(k),
                "Expected": v,
                "Actual": right_flattened[k]
            }
            found_diff = True

    return diff, found_diff

def handle_custom_mapping(k, custom_mapping_template) -> str:
    for key, val in custom_mapping_template.items():
        if key in k:
            k = k.replace(key, val)
            break
    return k

if __name__ == "__main__":
    args_len: int = len(sys.argv)

    # if args_len < 3 or args_len > 4: 
    #     sys.exit("usage: diff.py original_JSON new_JSON [custom_mappings_JSON]")

    # left: str = sys.argv[1]
    # right: str = sys.argv[2]
    
    custom_mappings: dict = {}

    # if args_len == 4:
    #     custom_mappings = sys.argv[3]
    #     with open(custom_mappings, 'r') as reader:
    #         custom_mappings: dict = json.loads(reader.read())

    custom_mappings = sys.argv[1]
    with open(custom_mappings, 'r') as reader:
        custom_mappings: dict = json.loads(reader.read())

    original_basepath = "original"
    new_basebath = "new"
    diff_basepath = "diff"
    original_JSON_files = os.listdir(original_basepath)

    count = 1
    l = len(original_JSON_files)

    for original_JSON_file in original_JSON_files:
        print("Computing diff for: " + original_JSON_file + " (" + str(count) + " of " + str(l) + ")")
        count += 1

        with open('{}/{}'.format(original_basepath, original_JSON_file), 'r') as f:
            left = json.loads(f.read())
    
        with open('{}/{}'.format(new_basebath, original_JSON_file), 'r') as f:
            right = json.loads(f.read())

        # pickup "PayLoad" section of left JSON for comparison
        left: dict = left["PayLoad"]

        # pickup "payLoad" section of right JSON for comparison
        right: dict = right["eventMessage"]["eventAttributes"]["dataElements"]["payLoad"] 
        
        diff, found_diff = json_diff(left, right, custom_mappings)

        if found_diff:
            with open('{}/{}'.format(diff_basepath, original_JSON_file), 'w') as f:
                # if found_diff == True:
                f.write(json.dumps(diff, indent = 2))
                # else:
                #     print("\tNo diff found for file: " + original_JSON_file)

    # with open(left, 'r') as reader:
    #     left = reader.read()

    # with open(right, 'r') as reader:
    #     right = reader.read()

    # left: dict = json.loads(left)
    # right: dict = json.loads(right)

    # # pickup "PayLoad" section of left JSON for comparison
    # left: dict = left["PayLoad"]

    # # pickup "payLoad" section of right JSON for comparison
    # right: dict = right["eventMessage"]["eventAttributes"]["dataElements"]["payLoad"]    

    # diff: dict = json_diff(left, right, custom_mappings)

    # print("Diff: ")
    # print(json.dumps(diff, indent=2))
